BAND SDK Draft
bandframework/rose pull request #38
Opened 2023-09-20 21:49 UTC by kylegodbey

Here's a draft of the BAND SDK. I think it's more or less good to go, I just need to know if we'll link a logo and what to do about the contact email. I prefer most contact to happen within Github

2023-09-20 22:13 UTC, mosesyhc requested changes
Agree with using github issues to handle support entirely. 

See in-file comment about README bug and installation guidelines.

2023-09-20 22:13 UTC, mosesyhc commented on rosebandsdk.md
On M2: 
1. READEME basic example breaks and needs an update.
2. Is there anywhere we instruct users to install with `nuclear-rose`, since `rose` is another package installable via pip?

2023-09-20 22:19 UTC, kylegodbey commented on rosebandsdk.md
1. Good catch. I'm not entirely sure we need a full example like that in the README since it's kinda complex, maybe we just point to the tutorial? @pabggpnMSU might have an opinion.

2. Maybe not, that's another important thing to add to the readme and the intro page to the docs.

2023-09-20 22:22 UTC, mosesyhc commented on rosebandsdk.md
Last thing I might add is a link to doc under R6 and/or add the link somewhere under the repository's About column.

2023-09-26 19:39 UTC, mosesyhc commented on rosebandsdk.md
@kylegodbey: The last bit I might insist is to change the **About column**. Then all is good.

2023-09-27 14:41 UTC, mosesyhc approved these changes
Commits in #26 has resolved comments here.

2023-09-27 22:19 UTC, merged